### PR TITLE
use llir/llvm@v0.3.0-pre2 for code generation

### PR DESCRIPTION
**Pull request by mewmew**
As an experiment, use the latest version of llir/llvm for code generation.

`codegen` test case output:

```
u@x1 ~/D/l/e/codegen> go test -v
=== RUN   TestBinaryFunction
```
```llvm
define i32 @main() {
; <label>:0
	%1 = call i32 @add(i32 10, i32 10)
	ret i32 %1
}

define i32 @add(i32 %x, i32 %y) {
; <label>:0
	%1 = add i32 10, 10
	ret i32 %1
}
```
```
--- PASS: TestBinaryFunction (0.00s)
PASS
ok  	github.com/elz-lang/elz/codegen	0.001s
```

Updates #5.

P.S. the test case was also updated to include a `ret` instruction for the `@main` function.

### CODE REVIEW

**Comment by mewmew** [comment]
re: https://github.com/elz-lang/elz/issues/5

**Comment by dannypsnl** [comment]
Thanks for your PR, I would need to take some time to compare c-binding & llir, basically, I think v0.3 is good for me, and work with c-binding is painful, have a nice day!

**Comment by mewmew** [comment]
> Thanks for your PR, I would need to take some time to compare c-binding & llir, basically, I think v0.3 is good for me, and work with c-binding is painful, have a nice day!

Of course!

Let me know if you reach any stumbling blocks and we could try to fix them together. Have a great day :)

**Comment by dannypsnl** [comment]
@mewmew Can you help me change the target branch to `llir` so I can merge it and compare with `master` branch? (And I can fix the conflict at `llir` branch) Thanks

**Comment by mewmew** [comment]
> @mewmew Can you help me change the target branch to llir so I can merge it and compare with master branch? (And I can fix the conflict at llir branch) Thanks

Of course!

**Comment by mewmew** [comment]
Closed in favour of https://github.com/elz-lang/elz/pull/115

**Pull request closed without merging**
